services:
    _defaults:
        public: false

    itmegastar_sms.prototype.provider.sms_ru:
        class: ITMegastar\Bundle\SmsBundle\Provider\SmsRuProvider

    itmegastar_sms.prototype.provider.sms_aero:
        class: ITMegastar\Bundle\SmsBundle\Provider\SmsAeroProvider

    itmegastar_sms.prototype.provider.sms_discount:
        class: ITMegastar\Bundle\SmsBundle\Provider\SmsDiscountProvider

    itmegastar_sms.prototype.provider.sms_center:
        class: ITMegastar\Bundle\SmsBundle\Provider\SmsCenterProvider

    itmegastar_sms.prototype.provider.message_bird:
        class: ITMegastar\Bundle\SmsBundle\Provider\MessageBirdProvider

    itmegastar_sms.provider.manager:
        class: ITMegastar\Bundle\SmsBundle\Service\ProviderManager

    ITMegastar\Bundle\SmsBundle\Service\ProviderManager: '@itmegastar_sms.provider.manager'

    itmegastar_sms.command.test_delivery:
        class: ITMegastar\Bundle\SmsBundle\Command\TestDeliveryCommand
        arguments: ['@itmegastar_sms.provider.manager']
        tags:
            - { name: 'console.command' }